version: '3.2'
services:
  lazy-panda-proto-gen:
    image: omaressameldin/proto-gen
    environment:
      - BUILD_PATH=${PROTO_BUILD_PATH}
      - OUTPUT_PATH=${PROTO_OUTPUT_PATH}
      - FILENAME=${PROTO_FILENAME}
    volumes:
      - type: bind
        target: ${PROTO_OUTPUT_PATH}
        source: ./app${PROTO_OUTPUT_PATH}
      - type: bind
        target: ${PROTO_BUILD_PATH}
        source: ./proto-gen${PROTO_BUILD_PATH}
  lazy-panda-upload-server:
    build:
      context: .
      args:
        - APP_SRC=${APP_SRC}
        - MODS=${MODS}
        - BUILD_FILE=${BUILD_FILE}
    command: sh -c "cp -r ${MODS}/. ${APP_SRC} && /${BUILD_FILE} --port=${PORT}"
    volumes:
      - type: bind
        target: ${APP_SRC}
        source: ./app
    ports:
      - "${PORT}:${PORT}"