// Code generated by protoc-gen-go. DO NOT EDIT.
// source: upload.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UploadStatusCode int32

const (
	UploadStatusCode_Unknown UploadStatusCode = 0
	UploadStatusCode_Ok      UploadStatusCode = 1
	UploadStatusCode_Failed  UploadStatusCode = 2
)

var UploadStatusCode_name = map[int32]string{
	0: "Unknown",
	1: "Ok",
	2: "Failed",
}

var UploadStatusCode_value = map[string]int32{
	"Unknown": 0,
	"Ok":      1,
	"Failed":  2,
}

func (x UploadStatusCode) String() string {
	return proto.EnumName(UploadStatusCode_name, int32(x))
}

func (UploadStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{0}
}

type UploadRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{0}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UploadRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type UploadFileRequest struct {
	// Types that are valid to be assigned to FileData:
	//	*UploadFileRequest_Content
	//	*UploadFileRequest_Meta
	FileData             isUploadFileRequest_FileData `protobuf_oneof:"fileData"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *UploadFileRequest) Reset()         { *m = UploadFileRequest{} }
func (m *UploadFileRequest) String() string { return proto.CompactTextString(m) }
func (*UploadFileRequest) ProtoMessage()    {}
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{1}
}

func (m *UploadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileRequest.Unmarshal(m, b)
}
func (m *UploadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileRequest.Marshal(b, m, deterministic)
}
func (m *UploadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileRequest.Merge(m, src)
}
func (m *UploadFileRequest) XXX_Size() int {
	return xxx_messageInfo_UploadFileRequest.Size(m)
}
func (m *UploadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileRequest proto.InternalMessageInfo

type isUploadFileRequest_FileData interface {
	isUploadFileRequest_FileData()
}

type UploadFileRequest_Content struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3,oneof"`
}

type UploadFileRequest_Meta struct {
	Meta *Metadata `protobuf:"bytes,2,opt,name=meta,proto3,oneof"`
}

func (*UploadFileRequest_Content) isUploadFileRequest_FileData() {}

func (*UploadFileRequest_Meta) isUploadFileRequest_FileData() {}

func (m *UploadFileRequest) GetFileData() isUploadFileRequest_FileData {
	if m != nil {
		return m.FileData
	}
	return nil
}

func (m *UploadFileRequest) GetContent() []byte {
	if x, ok := m.GetFileData().(*UploadFileRequest_Content); ok {
		return x.Content
	}
	return nil
}

func (m *UploadFileRequest) GetMeta() *Metadata {
	if x, ok := m.GetFileData().(*UploadFileRequest_Meta); ok {
		return x.Meta
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UploadFileRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UploadFileRequest_OneofMarshaler, _UploadFileRequest_OneofUnmarshaler, _UploadFileRequest_OneofSizer, []interface{}{
		(*UploadFileRequest_Content)(nil),
		(*UploadFileRequest_Meta)(nil),
	}
}

func _UploadFileRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UploadFileRequest)
	// fileData
	switch x := m.FileData.(type) {
	case *UploadFileRequest_Content:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Content)
	case *UploadFileRequest_Meta:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Meta); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UploadFileRequest.FileData has unexpected type %T", x)
	}
	return nil
}

func _UploadFileRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UploadFileRequest)
	switch tag {
	case 1: // fileData.content
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.FileData = &UploadFileRequest_Content{x}
		return true, err
	case 2: // fileData.meta
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Metadata)
		err := b.DecodeMessage(msg)
		m.FileData = &UploadFileRequest_Meta{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UploadFileRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UploadFileRequest)
	// fileData
	switch x := m.FileData.(type) {
	case *UploadFileRequest_Content:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Content)))
		n += len(x.Content)
	case *UploadFileRequest_Meta:
		s := proto.Size(x.Meta)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Metadata struct {
	Auth                 string   `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileType             string   `protobuf:"bytes,3,opt,name=fileType,proto3" json:"fileType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{2}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *Metadata) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Metadata) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

type UploadStatusResponse struct {
	Api                  string           `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Url                  string           `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Message              string           `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Code                 UploadStatusCode `protobuf:"varint,4,opt,name=Code,proto3,enum=v1.UploadStatusCode" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UploadStatusResponse) Reset()         { *m = UploadStatusResponse{} }
func (m *UploadStatusResponse) String() string { return proto.CompactTextString(m) }
func (*UploadStatusResponse) ProtoMessage()    {}
func (*UploadStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{3}
}

func (m *UploadStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadStatusResponse.Unmarshal(m, b)
}
func (m *UploadStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadStatusResponse.Marshal(b, m, deterministic)
}
func (m *UploadStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadStatusResponse.Merge(m, src)
}
func (m *UploadStatusResponse) XXX_Size() int {
	return xxx_messageInfo_UploadStatusResponse.Size(m)
}
func (m *UploadStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadStatusResponse proto.InternalMessageInfo

func (m *UploadStatusResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UploadStatusResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UploadStatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UploadStatusResponse) GetCode() UploadStatusCode {
	if m != nil {
		return m.Code
	}
	return UploadStatusCode_Unknown
}

type DeleteRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DeleteResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{5}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func init() {
	proto.RegisterEnum("v1.UploadStatusCode", UploadStatusCode_name, UploadStatusCode_value)
	proto.RegisterType((*UploadRequest)(nil), "v1.UploadRequest")
	proto.RegisterType((*UploadFileRequest)(nil), "v1.UploadFileRequest")
	proto.RegisterType((*Metadata)(nil), "v1.Metadata")
	proto.RegisterType((*UploadStatusResponse)(nil), "v1.UploadStatusResponse")
	proto.RegisterType((*DeleteRequest)(nil), "v1.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "v1.DeleteResponse")
}

func init() { proto.RegisterFile("upload.proto", fileDescriptor_91b94b655bd2a7e5) }

var fileDescriptor_91b94b655bd2a7e5 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcf, 0x4f, 0xf2, 0x40,
	0x10, 0xa5, 0xa5, 0x29, 0x7c, 0xc3, 0x8f, 0x94, 0x09, 0x5f, 0xd2, 0xf4, 0x44, 0xf6, 0xd4, 0x78,
	0xc0, 0x00, 0x47, 0xe3, 0x45, 0x09, 0xe1, 0x82, 0x26, 0x45, 0xbc, 0x9a, 0x95, 0x8e, 0xda, 0x50,
	0xda, 0x4a, 0xb7, 0x18, 0x0f, 0xfa, 0xb7, 0x9b, 0xdd, 0xb2, 0x82, 0x28, 0xb7, 0x99, 0xf7, 0x76,
	0xde, 0xbc, 0xd7, 0x0e, 0x34, 0x8b, 0x2c, 0x4e, 0x79, 0xd8, 0xcf, 0x36, 0xa9, 0x48, 0xd1, 0xdc,
	0x0e, 0xd8, 0x25, 0xb4, 0x16, 0x0a, 0x0b, 0xe8, 0xb5, 0xa0, 0x5c, 0xa0, 0x03, 0x55, 0x9e, 0x45,
	0xae, 0xd1, 0x33, 0xfc, 0x7f, 0x81, 0x2c, 0xd1, 0x83, 0xfa, 0x53, 0x14, 0x53, 0xc2, 0xd7, 0xe4,
	0x9a, 0x0a, 0xfe, 0xee, 0xd9, 0x03, 0x74, 0xca, 0xf1, 0x49, 0x14, 0x93, 0x96, 0xf0, 0xa0, 0xb6,
	0x4c, 0x13, 0x41, 0x89, 0x50, 0x32, 0xcd, 0x69, 0x25, 0xd0, 0x00, 0x32, 0xb0, 0xd6, 0x24, 0xb8,
	0x12, 0x6a, 0x0c, 0x9b, 0xfd, 0xed, 0xa0, 0x3f, 0x23, 0xc1, 0x43, 0x2e, 0xf8, 0xb4, 0x12, 0x28,
	0xee, 0x0a, 0xca, 0x85, 0x63, 0x2e, 0x38, 0xbb, 0x87, 0xba, 0xe6, 0x11, 0xc1, 0xe2, 0x85, 0x78,
	0xd9, 0x79, 0x53, 0xb5, 0x36, 0x77, 0x73, 0x64, 0x4e, 0xf6, 0x9a, 0xbb, 0x7b, 0xcf, 0xc8, 0xad,
	0xee, 0x39, 0xd9, 0xb3, 0x4f, 0xe8, 0x96, 0xc6, 0xe7, 0x82, 0x8b, 0x22, 0x0f, 0x28, 0xcf, 0xd2,
	0x24, 0xa7, 0x3f, 0xe2, 0x3b, 0x50, 0x2d, 0x36, 0xf1, 0x4e, 0x5c, 0x96, 0xe8, 0x42, 0x6d, 0x46,
	0x79, 0xce, 0x9f, 0xb5, 0xac, 0x6e, 0xd1, 0x07, 0xeb, 0x3a, 0x0d, 0xc9, 0xb5, 0x7a, 0x86, 0xdf,
	0x1e, 0x76, 0x65, 0xba, 0xc3, 0x2d, 0x92, 0x0b, 0xd4, 0x0b, 0x36, 0x82, 0xd6, 0x98, 0x62, 0x12,
	0x74, 0xfa, 0xbb, 0xff, 0x5a, 0xcc, 0x18, 0xb4, 0xf5, 0xd0, 0x29, 0xbb, 0x67, 0x23, 0x70, 0x8e,
	0x57, 0x62, 0x03, 0x6a, 0x8b, 0x64, 0x95, 0xa4, 0x6f, 0x89, 0x53, 0x41, 0x1b, 0xcc, 0xdb, 0x95,
	0x63, 0x20, 0x80, 0x3d, 0xe1, 0x51, 0x4c, 0xa1, 0x63, 0x0e, 0x3f, 0xf4, 0x15, 0xcc, 0x69, 0xb3,
	0x8d, 0x96, 0x84, 0x17, 0x60, 0x97, 0x00, 0xfe, 0xdf, 0x87, 0x38, 0xf8, 0xc7, 0x9e, 0x7b, 0x9c,
	0x4d, 0x5b, 0xf2, 0x0d, 0x3c, 0x07, 0xbb, 0xb4, 0x89, 0x1d, 0xf9, 0xea, 0x47, 0x4e, 0x0f, 0x0f,
	0xa1, 0x72, 0xe4, 0xd1, 0x56, 0xf7, 0x38, 0xfa, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x2f, 0x3d,
	0x59, 0x9f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UploadServiceClient is the client API for UploadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UploadServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (UploadService_UploadClient, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type uploadServiceClient struct {
	cc *grpc.ClientConn
}

func NewUploadServiceClient(cc *grpc.ClientConn) UploadServiceClient {
	return &uploadServiceClient{cc}
}

func (c *uploadServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (UploadService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UploadService_serviceDesc.Streams[0], "/v1.UploadService/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &uploadServiceUploadClient{stream}
	return x, nil
}

type UploadService_UploadClient interface {
	Send(*UploadFileRequest) error
	CloseAndRecv() (*UploadStatusResponse, error)
	grpc.ClientStream
}

type uploadServiceUploadClient struct {
	grpc.ClientStream
}

func (x *uploadServiceUploadClient) Send(m *UploadFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *uploadServiceUploadClient) CloseAndRecv() (*UploadStatusResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadStatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *uploadServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/v1.UploadService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploadServiceServer is the server API for UploadService service.
type UploadServiceServer interface {
	Upload(UploadService_UploadServer) error
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterUploadServiceServer(s *grpc.Server, srv UploadServiceServer) {
	s.RegisterService(&_UploadService_serviceDesc, srv)
}

func _UploadService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UploadServiceServer).Upload(&uploadServiceUploadServer{stream})
}

type UploadService_UploadServer interface {
	SendAndClose(*UploadStatusResponse) error
	Recv() (*UploadFileRequest, error)
	grpc.ServerStream
}

type uploadServiceUploadServer struct {
	grpc.ServerStream
}

func (x *uploadServiceUploadServer) SendAndClose(m *UploadStatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *uploadServiceUploadServer) Recv() (*UploadFileRequest, error) {
	m := new(UploadFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UploadService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UploadService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UploadService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UploadService",
	HandlerType: (*UploadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _UploadService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _UploadService_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "upload.proto",
}
